=== elita001/XMLExamples/XmlParsers/src/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/Shutov_schema"
	xmlns:tns="http://www.example.org/Shutov_schema">
	<element name="categories" type="tns:categories"></element>
	<complexType name="categories">
			<sequence>
				<element name="category" type="tns:category" minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	<complexType name="category">		
		<sequence>
			<element name="subcategory" type="tns:subcategory" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>	
	<complexType name="subcategory">		
		<sequence>
			<element name="product" type="tns:product" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	<complexType name="product">		
		<sequence>
			<element name="manufacturer" type="string"></element>
			<element name="model" type="tns:model"></element>
			<element name="date" type="tns:date"></element>
			<element name="colour" type="string"></element>
			<element name="price" type="tns:price"></element>
			<choice>			
				<element name="quantity" type="tns:quantity"></element>							
				<element name="available" type="boolean" fixed="false">				
				</element>
			</choice>			
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>	
	<simpleType name="model">
		<restriction base="string">
			<pattern value="([a-zA-Z]{2})([0-9]{3})"></pattern>
		</restriction>
	</simpleType>
	<simpleType name="date">
		<restriction base="string">
			<pattern value="((0[1-9])|([12][0-9])|(3[01]))-((0[1-9])|(1[0-2]))-([12]([0-9]{3}))"></pattern>
		</restriction>
	</simpleType>
	<simpleType name="price">
		<restriction base="double">
			<minInclusive value="0.0"></minInclusive>
		</restriction>
	</simpleType>
	<simpleType name="quantity">
		<restriction base="int">
			<minExclusive value="0"></minExclusive>
		</restriction>
	</simpleType>				
</schema>

=== elita001/XMLExamples/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:categories xmlns:tns="http://www.example.org/Shutov_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Shutov_schema products.xsd ">
	<category name="cameras and videocameras">
		<subcategory name="cameras">
			<product name="camera Canon">
				<manufacturer>Russia</manufacturer>
				<model>ba123</model>
				<date>21-12-2013</date>
				<colour>red</colour>
				<price>2000.39</price>
				<quantity>1</quantity>
			</product>
			<product name="camera Sony">
				<manufacturer>USA</manufacturer>
				<model>aa333</model>
				<date>12-11-2013</date>
				<colour>yellow</colour>
				<price>1500.00</price>
				<quantity>28</quantity>
			</product>
		</subcategory>		
		<subcategory name="videocameras">
			<product name="videocamera Canon">
				<manufacturer>Germany</manufacturer>
				<model>oi872</model>
				<date>05-02-2014</date>
				<colour>green</colour>
				<price>3500.00</price>
				<available>false</available>
			</product>
		</subcategory>
	</category>
	<category name="computer accessories">
		<subcategory name="memory modules">
		</subcategory>
	</category>
	<category name="games">
	</category>
</tns:categories>
